# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'Investo' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
    
  use_react_native!(:path => config["reactNativePath"])

  # Pods for Investo

  target 'InvestoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
